"""
Register this edge device with ONA Cloud
Run this once to get device credentials
"""

import httpx
import json
from pathlib import Path

# Cloud API URL
CLOUD_API = "https://ona-diagnostic-production.up.railway.app/api/v1"

def register_device():
    """Register device with cloud and save credentials"""

    print("Registering device with ONA Cloud...")
    print(f"API: {CLOUD_API}")
    print()

    # First, seed the database with tenant/site/device
    seed_data = {
        "tenant_name": "Ona Kenya",
        "site_name": "Test Clinic",
        "site_code": "TEST001",
        "country": "KE",
        "device_name": "ONA-DEV-001"
    }

    try:
        response = httpx.post(
            f"{CLOUD_API}/seed",
            json=seed_data,
            timeout=30.0
        )

        if response.status_code == 200:
            result = response.json()
            print("Registration successful!")
            print()
            print(f"  Tenant ID:  {result['tenant_id']}")
            print(f"  Site ID:    {result['site_id']}")
            print(f"  Device ID:  {result['device_id']}")
            print(f"  Token:      {result['device_token']}")
            print()

            # Save to .env file
            env_path = Path(__file__).parent.parent / '.env'
            env_content = f"""# ONA Edge Configuration
# Generated by register_device.py

# Device credentials (from cloud registration)
ONA_DEVICE_ID={result['device_id']}
ONA_SITE_ID={result['site_id']}
ONA_TENANT_ID={result['tenant_id']}
ONA_API_KEY={result['device_token']}

# Cloud API
ONA_CLOUD_API={CLOUD_API}

# Local settings
ONA_DICOM_PORT=11112
ONA_UI_PORT=8080
"""
            env_path.write_text(env_content)
            print(f"Saved credentials to: {env_path}")
            print()
            print("Restart the edge software to apply the new configuration.")

            return result

        else:
            print(f"Registration failed: {response.status_code}")
            print(response.text)
            return None

    except Exception as e:
        print(f"Error: {e}")
        return None


if __name__ == "__main__":
    register_device()
